language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - ant-optional
script:
  - ant testall
deploy:
  provider: pages
  repo: git@github.com:FreeCol/FreeCol-Reports.git
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: "build/report"
  on:
    branch: master
